services:
  app:
    build: .
    container_name: app_container
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:16
    container_name: postgres_container
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data  
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # add file to this folder and they will execute on startup

volumes:
  pg_data:
